.github/przepływy worki/pusty.yml# To jest podstawowy przepływ pracy, który pomoże ci zacząć od działańnazwass: Ci

# Kontrole, gdy przepływ pracy będzie przebiegał
na:
  # Trybunaje przepływ pracy na pchaniu lub ciągnąć wydarzenia prośby, ale tylko dla "głównego" oddziału
  pchnąć :
  oddziały : [ "głównym" ]
 pull_requestpull_request:
  oddziały : [ "głównym" ]

  # Pozwala na ręczne prowadzenie tego przepływu pracy z zakładki "Akcji"
  przepływ workworkworki_wysyłka :

# Ruch przepływu pracy składa się z jednej lub więcej miejsc pracy, które mogą prowadzić kolejno lub równolegle
miejsca pracy:
  # Ten przepływ pracy zawiera jedną pracę zwaną "build"
  budowa :
    # Rodzaj biegacza, który będzie trwała praca
 runs-on : Najnowszy ubuntu

    # Kroki stanowią sekwencję zadań, które zostaną wykonane w ramach pracy
  kroki :
      # Sprawdź swoją repozytorię pod $GITHUB_WORKSPACE, więc twoja praca może do niego uzyskać dostęp
 - zastosowania: działania/kontrola@v4

      # Prowadzi jedno polecenie za pomocą powłoki starców
 - nazwa: Uruchom scenariusz jednolinii
  Uciekaj : echo Witam, świat!

      # Prowadzi zestaw poleceń za pomocą powłoki starców
 - nazwa: Uruchom wieloliniowy scenariusz
  Uciekaj : |
  echo Dodaj inne działania do budowy,  
 test echo i rozesłać swój projekt. 
